### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by nagaoo0** [iMasonite/KenetiMinecraft#1]
Would you happen to have a compiled version ? I can't get it to compile correctly. 
Only for testing purposes, I am planning a massive LAN party with my university and we voted for a tekkit lite hardcore difficulty game so I am preparing the server. By the way Keneti server is amazing

**Comment by iMasonite** [comment]
This repo only contains pom and locale information, it doesn't contain all the class files needed to compile. This is a semi-private repo in this sense and I can't share the core files unfortunately.

**Comment by nagaoo0** [comment]
Oh yeah sure I understand, I get its a lot of work.
Is there a plugin that you know of that is similar to your limits plugin? I can't seem to find anything like it; that limits the amount of blocks placed per group/rank

**Comment by iMasonite** [comment]
Unfortunately not, it was several months in the making as there were no solutions out there that came remotely close. I had to create the whole thing form scratch.
